import Mathlib


/-!
This file extends the current DSL with:
1. A function `fNN` on nonnegative reals defined by `f(x) = sqrt(2 + sqrt(x))`.
2. Sequences on ℝ≥0 built by primitive recursion from `fNN`, including a one-based indexing variant.
3. A predicate `StrictlyBoundedAboveBy` for real sequences being strictly bounded above.
4. A real sequence `sqrtDiffSeq i = sqrt(i + 1) − sqrt(i)`.
5. A relation `TopologicalSpace.comparable` expressing comparability of two topologies by inclusion.

All definitions are registered with `simp` as requested.
-/

noncomputable section

open Real
open scoped NNReal

namespace CDG

/-- The function on nonnegative real numbers given by `x ↦ √(2 + √x)`. -/
@[simp]
def fNN (x : ℝ≥0) : ℝ≥0 :=
  ⟨Real.sqrt ((2 : ℝ) + Real.sqrt x), Real.sqrt_nonneg _⟩

/-- The nonnegative real number `√2`. -/
@[simp]
def sqrtTwoNN : ℝ≥0 :=
  ⟨Real.sqrt (2 : ℝ), Real.sqrt_nonneg 2⟩

/-- A 0-based sequence on ℝ≥0 defined recursively by
`seq0 0 = √2` and `seq0 (n+1) = fNN (seq0 n)`. -/
@[simp]
def seq0 : ℕ → ℝ≥0
  | 0 => sqrtTwoNN
  | n+1 => fNN (seq0 n)

/-- A 1-based sequence on ℝ≥0 following the recurrence `s_{n+1} = fNN (s_n)` with
initial term `s_1 = √2`. It is realized by shifting the 0-based sequence:
`seq1 n = seq0 (n - 1)`, hence `seq1 1 = √2`. -/
@[simp]
def seq1 (n : ℕ) : ℝ≥0 :=
  seq0 (n - 1)

/-- A predicate expressing that a sequence of real numbers is strictly bounded above by `c`,
i.e. `∀ n, s n < c`. -/
@[simp]
def StrictlyBoundedAboveBy (s : ℕ → ℝ) (c : ℝ) : Prop :=
  ∀ n, s n < c

/-- The real sequence `sqrtDiffSeq i = √(i + 1) − √i`. -/
@[simp]
def sqrtDiffSeq (i : ℕ) : ℝ :=
  Real.sqrt ((i : ℝ) + 1) - Real.sqrt (i : ℝ)

end CDG

/-- Two topologies on the same type are comparable if one is included in the other
(i.e. `t ≤ u ∨ u ≤ t`). -/
@[simp]
def TopologicalSpace.comparable {α : Type*} (t u : TopologicalSpace α) : Prop :=
  t ≤ u ∨ u ≤ t


/-!
This extension adds:

1. A predicate `TopologicalSpace.notComparable` expressing that two topologies on the same
   type are not comparable by inclusion.

2. A predicate `CDG.IsSubbasisFor` stating that a given family of subsets is a subbasis
   for a topology (i.e., the topology is generated by that family).

3. The lower limit (Sorgenfrey) topology on `ℝ`, generated by the family of half-open
   intervals `[a, b)`.

4. The K-topology on `ℝ`, generated by the family consisting of all open intervals
   `(a, b)` together with the punctured intervals `(a, b) \ K`, where
   `K = { 1/n | n ∈ ℕ+, i.e., n : PNat }`.

5. The topology on `ℝ` generated by open intervals with rational endpoints.

All definitions are registered with `simp` as requested.
-/

noncomputable section

open Real

/-- Two topologies on the same type are not comparable by inclusion
(i.e. neither `t ≤ u` nor `u ≤ t` holds). -/
@[simp]
def TopologicalSpace.notComparable {α : Type*} (t u : TopologicalSpace α) : Prop :=
  ¬ TopologicalSpace.comparable t u

namespace CDG

/-- A family `S : Set (Set X)` is a subbasis for a topology `t` on `X` if `t` is the
topology generated from `S`. -/
@[simp]
def IsSubbasisFor {X : Type*} (S : Set (Set X)) (t : TopologicalSpace X) : Prop :=
  t = TopologicalSpace.generateFrom S

/-- The generating family for the lower limit (Sorgenfrey) topology on `ℝ`:
all half-open intervals `[a, b)` with `a < b`. -/
@[simp]
def lowerLimitGeneratingSets : Set (Set ℝ) :=
  {U | ∃ a b : ℝ, a < b ∧ U = Set.Ico a b}

/-- The lower limit (Sorgenfrey) topology on `ℝ`, generated by the family
`{ [a, b) | a < b }`. -/
@[simp]
def realLowerLimitTopology : TopologicalSpace ℝ :=
  TopologicalSpace.generateFrom lowerLimitGeneratingSets

/-- The set `K := { 1/n | n ∈ ℕ+ } ⊆ ℝ`, used in the definition of the K-topology. -/
@[simp]
def K_natRecip : Set ℝ :=
  {x | ∃ n : PNat, x = (1 : ℝ) / ((n : ℕ) : ℝ)}

/-- The generating family for the K-topology on `ℝ`:
all open intervals `(a, b)` and the punctured intervals `(a, b) \ K`. -/
@[simp]
def KTopologyGeneratingSets : Set (Set ℝ) :=
  {U | ∃ a b : ℝ, a < b ∧ (U = Set.Ioo a b ∨ U = Set.Ioo a b \ K_natRecip)}

/-- The K-topology on `ℝ`, generated by the family consisting of all sets
of the form `(a, b)` and `(a, b) \ K`, where `K = { 1/n | n ∈ ℕ+ }`. -/
@[simp]
def realKTopology : TopologicalSpace ℝ :=
  TopologicalSpace.generateFrom KTopologyGeneratingSets

/-- The generating family for the topology on `ℝ` with a basis of intervals having
rational endpoints: `Ioo a b` with `a, b ∈ ℚ` and `a < b`. -/
@[simp]
def rationalIooGeneratingSets : Set (Set ℝ) :=
  {U | ∃ a b : ℚ, a < b ∧ U = Set.Ioo (a : ℝ) (b : ℝ)}

/-- The topology on `ℝ` generated by the basis of open intervals with rational endpoints. -/
@[simp]
def realTopologyFromRationalIntervals : TopologicalSpace ℝ :=
  TopologicalSpace.generateFrom rationalIooGeneratingSets

end CDG


/-!
This extension adds:

1. A sequence of functions on the unit interval `[0,1]`, `powSeqOnUnitInterval n x = x^n`.
2. A predicate `PointwiseConvergesOn` for pointwise convergence of a sequence of functions
   on a set.
3. The pointwise limit function `powLimitOnUnitInterval` for the sequence `x^n` on `[0,1]`,
   defined by `0` for `x < 1` and `1` at `x = 1`.
4. A predicate `IsLimitPoint` for limit points of subsets in a topological space.
5. A predicate `LimitPointCompact` expressing limit point compactness of a topological space.

All definitions are registered with `simp` as requested.
-/

noncomputable section

open Real Filter Set TopologicalSpace

namespace CDG

/-- The sequence of functions on the unit interval `[0,1]` given by
`(powSeqOnUnitInterval n) x = x^n`. The domain is the subtype `↥(Icc 0 1)`. -/
@[simp]
def powSeqOnUnitInterval : ℕ → (Set.Icc (0 : ℝ) 1 → ℝ) :=
  fun n x => (x : ℝ) ^ n

/-- The pointwise limit function on `[0,1]` associated to the sequence `x^n`:
it is `0` for `x < 1` and `1` at `x = 1`. -/
@[simp]
def powLimitOnUnitInterval : (Set.Icc (0 : ℝ) 1) → ℝ :=
  fun x => if (x : ℝ) < 1 then 0 else 1

/-- Pointwise convergence on a set: a sequence of functions `F : ℕ → X → ℝ` converges
pointwise on `S` to `g : X → ℝ` if `∀ x ∈ S, Tendsto (fun n => F n x) atTop (nhds (g x))`. -/
@[simp]
def PointwiseConvergesOn {X : Type*} (F : ℕ → X → ℝ) (g : X → ℝ) (S : Set X) : Prop :=
  ∀ x ∈ S, Tendsto (fun n => F n x) atTop (nhds (g x))

/-- A point `x` is a limit point of a subset `A` of a topological space `X` if every
neighborhood of `x` meets `A \ {x}`. -/
@[simp]
def IsLimitPoint {X : Type*} [TopologicalSpace X] (A : Set X) (x : X) : Prop :=
  ∀ U ∈ nhds x, (U ∩ (A \ {x})).Nonempty

/-- A topological space is limit point compact if every infinite subset has a limit point. -/
@[simp]
def LimitPointCompact {X : Type*} [TopologicalSpace X] : Prop :=
  ∀ A : Set X, A.Infinite → ∃ x : X, IsLimitPoint A x

end CDG


noncomputable section

open Set Filter TopologicalSpace
open scoped ENNReal

namespace CDG

/-! 1. Nested (decreasing) sequences of closed nonempty subsets -/

/-- A nested (decreasing) sequence `C : ℕ → Set X` of closed, nonempty sets in a
topological space: `Antitone C ∧ (∀ n, IsClosed (C n)) ∧ (∀ n, (C n).Nonempty)`. -/
@[simp]
def NestedClosedNonempty {X : Type*} [TopologicalSpace X] (C : ℕ → Set X) : Prop :=
  Antitone C ∧ (∀ n : ℕ, IsClosed (C n)) ∧ (∀ n : ℕ, (C n).Nonempty)

/-- The property that every nested (decreasing) sequence of closed nonempty subsets of `X`
has nonempty intersection `⋂ n, C n`. -/
@[simp]
def NestedClosedNonemptyInterNonempty {X : Type*} [TopologicalSpace X] : Prop :=
  ∀ (C : ℕ → Set X),
    Antitone C →
    (∀ n : ℕ, IsClosed (C n)) →
    (∀ n : ℕ, (C n).Nonempty) →
    (⋂ n, C n).Nonempty


/-! 2. The supremum edistance on `[0,1]^ω` and the induced uniform topology -/

/-- The unit interval `[0,1]` seen as a subtype of `ℝ`. -/
abbrev UnitInterval : Type := Set.Icc (0 : ℝ) 1

/-- The countable product `[0,1]^ω`, implemented as sequences with values in the unit interval. -/
abbrev UnitIntervalSeq : Type := ℕ → UnitInterval

/-- The `ℝ≥0∞`-valued supremum edistance on `[0,1]^ω` written explicitly as an `iSup`. -/
@[simp]
def supEdistOnUnitIntervalSeq (x y : UnitIntervalSeq) : ℝ≥0∞ :=
  iSup (fun n : ℕ => edist (x n) (y n))

/-- The uniform space on `[0,1]^ω` coming from the (supremum) `EMetricSpace` Pi-instance. -/
abbrev unitIntervalSeqUniformSpace : UniformSpace UnitIntervalSeq := inferInstance

/-- The topology on `[0,1]^ω` induced by the uniform structure coming from the supremum edistance. -/
abbrev unitIntervalSeqUniformTopology : TopologicalSpace UnitIntervalSeq := inferInstance

end CDG
