import Mathlib

open Real Filter
noncomputable section


/-- The recursively defined sequence `f : ℕ → ℝ` with
`f 0 = sqrt 2` and `f (n + 1) = sqrt (2 + sqrt (f n))`. -/
@[simp]
def f : ℕ → ℝ
  | 0 => sqrt 2
  | (n + 1) => sqrt (2 + sqrt (f n))


/-- The telescoping difference between consecutive square roots, `√(n+1) - √n`. -/
@[simp]
def g (n : ℕ) : ℝ := sqrt (n + 1) - sqrt n


/-- Predicate stating that a family `T : Set (Set X)` forms a topology on `X`:
contains `Set.univ`, is closed under finite intersections, and arbitrary unions. -/
@[simp]
def is_topology (X : Type*) (T : Set (Set X)) :=
  Set.univ ∈ T ∧
  (∀ s t, s ∈ T → t ∈ T → s ∩ t ∈ T) ∧
  (∀ s, (∀ t ∈ s, t ∈ T) → Set.sUnion s ∈ T)


/-- The lower limit (Sorgenfrey) topology on a preordered type `X`,
generated by half‑open intervals `[a, b)`. -/
@[simp]
def lower_limit_topology (X : Type) [Preorder X] :=
  TopologicalSpace.generateFrom {S : Set X | ∃ a b, a < b ∧ S = Set.Ico a b}


/-- The lower limit (Sorgenfrey) topology on `ℝ`. -/
@[simp]
def Rl := lower_limit_topology ℝ


/-- The set `K = { 1/n | n : ℕ }` of reciprocals of natural numbers. -/
@[simp]
def K : Set ℝ := {r | ∃ n : ℕ, r = 1 / n}


/-- The topology on `ℝ` generated by usual open intervals `(a, b)`
and by punctured intervals `(a, b) \ K`. -/
@[simp]
def K_topology :=
  TopologicalSpace.generateFrom
    ({S : Set ℝ | ∃ a b, a < b ∧ S = Set.Ioo a b} ∪
    {S : Set ℝ | ∃ a b, a < b ∧ S = Set.Ioo a b \ K})


/-- Predicate: `x` is a rational real number. -/
@[simp]
def rational (x : ℝ) := x ∈ Set.range ((↑) : ℚ → ℝ)


/-- The closed unit interval `[0, 1] ⊆ ℝ`. -/
@[simp]
abbrev I : Set ℝ := Set.Icc 0 1


/-- Countable compactness: every countable open cover has a finite subcover. -/
@[simp]
def countably_compact (X : Type*) [TopologicalSpace X] :=
  ∀ U : ℕ → Set X,
  (∀ i, IsOpen (U i)) ∧ ((Set.univ : Set X) ⊆ ⋃ i, U i) →
  (∃ t : Finset ℕ, (Set.univ : Set X) ⊆ ⋃ i ∈ t, U i)


/-- Limit point compactness: every infinite subset of `X` has a cluster point. -/
@[simp]
def limit_point_compact (X : Type*) [TopologicalSpace X] :=
  ∀ U : Set X, Infinite U → ∃ x ∈ U, ClusterPt x (𝓟 U)

end