import Mathlib


/-!
This file extends Mathlib with a small, self-contained collection of reusable
definitions used in undergraduate-level formalization tasks. The design
emphasizes generality, concise naming, and consistency with Mathlib conventions.

Contents:

1. Iterated square-root map on ℝ≥0 and a recursive sequence:
   - `nnrealSqrt2PlusSqrt` : x ↦ √(2 + √x) on ℝ≥0
   - `nnrealSqrt2`         : the nonnegative real √2
   - `nnrealIterSqrtSeq`   : the sequence defined by s₀ = √2, s_{n+1} = √(2+√(sₙ))

2. Simple sequence predicates and examples:
   - `StrictlyBoundedAboveBy` : strict upper bound predicate for sequences
   - `sqrtSuccDiff`           : the real sequence n ↦ √(n+1) - √n

3. Comparability of topologies:
   - `TopologiesComparable` : t ≤ u ∨ u ≤ t

4. Subbasis and generated topologies on ℝ:
   - `IsSubbasisFor` : a family is a subbasis for a topology if the topology is generated from it
   - `LowerLimitSubbasis` and `sorgenfreyTopology` (lower limit / Sorgenfrey line)
   - `KNatRecip`, `KTopologySubbasis`, and `kTopology` (K-topology on ℝ)
   - `RationalIooSubbasis` and `realTopologyFromRationalIoo` (topology from rational intervals)

5. Pointwise convergence on a set and limit points:
   - `UnitInterval` : the type Icc 0 1
   - `powSeqOnUnitInterval` : the sequence of functions x ↦ x^n on the unit interval
   - `powLimitOnUnitInterval` : its pointwise limit
   - `PointwiseConvergesOn` : pointwise convergence on a set
   - `IsLimitPoint` and `LimitPointCompact` : limit points and limit point compactness

6. Nested closed nonempty families:
   - `NestedClosedNonempty` : antitone closed nonempty families
   - `NestedClosedNonemptyInterNonempty` : their intersection is nonempty

All definitions are marked with `@[simp]` as requested.
-/

noncomputable section

open Real Filter Set TopologicalSpace
open scoped NNReal

/-- The function on ℝ≥0 given by `x ↦ √(2 + √x)`. -/
@[simp]
def nnrealSqrt2PlusSqrt (x : ℝ≥0) : ℝ≥0 :=
  ⟨Real.sqrt ((2 : ℝ) + Real.sqrt x), Real.sqrt_nonneg _⟩

/-- The nonnegative real number `√2`. -/
@[simp]
def nnrealSqrt2 : ℝ≥0 :=
  ⟨Real.sqrt (2 : ℝ), Real.sqrt_nonneg 2⟩

/-- The recursively defined sequence on ℝ≥0:
`s 0 = √2` and `s (n+1) = √(2 + √(s n))`. -/
@[simp]
def nnrealIterSqrtSeq : ℕ → ℝ≥0
  | 0 => nnrealSqrt2
  | n+1 => nnrealSqrt2PlusSqrt (nnrealIterSqrtSeq n)

/-- A predicate expressing that a sequence `s : ℕ → α` is strictly bounded above by `c`,
i.e. `∀ n, s n < c`. -/
@[simp]
def StrictlyBoundedAboveBy {α : Type*} [LT α] (s : ℕ → α) (c : α) : Prop :=
  ∀ n, s n < c

/-- The real sequence `n ↦ √(n + 1) − √n`. -/
@[simp]
def sqrtSuccDiff (n : ℕ) : ℝ :=
  Real.sqrt ((n : ℝ) + 1) - Real.sqrt (n : ℝ)

/-- Two topologies on the same type are comparable if one is included in the other
(i.e. `t ≤ u ∨ u ≤ t`). -/
@[simp]
def TopologiesComparable {α : Type*} (t u : TopologicalSpace α) : Prop :=
  t ≤ u ∨ u ≤ t

/-- A family `S : Set (Set X)` is a subbasis for a topology `t` on `X` if
`t` is generated from `S`. -/
@[simp]
def IsSubbasisFor {X : Type*} (S : Set (Set X)) (t : TopologicalSpace X) : Prop :=
  t = TopologicalSpace.generateFrom S

/-- The generating family for the lower limit (Sorgenfrey) topology on `ℝ`:
all half-open intervals `[a, b)` with `a < b`. -/
@[simp]
def LowerLimitSubbasis : Set (Set ℝ) :=
  {U | ∃ a b : ℝ, a < b ∧ U = Set.Ico a b}

/-- The lower limit (Sorgenfrey) topology on `ℝ`,
generated by `{ [a, b) | a < b }`. -/
@[simp]
def sorgenfreyTopology : TopologicalSpace ℝ :=
  TopologicalSpace.generateFrom LowerLimitSubbasis

/-- The set `K := { 1/n | n ∈ ℕ+ } ⊆ ℝ`, used in the definition of the K-topology. -/
@[simp]
def KNatRecip : Set ℝ :=
  {x | ∃ n : PNat, x = (1 : ℝ) / ((n : ℕ) : ℝ)}

/-- The generating family for the K-topology on `ℝ`:
all open intervals `(a, b)` and the punctured intervals `(a, b) \ K`. -/
@[simp]
def KTopologySubbasis : Set (Set ℝ) :=
  {U | ∃ a b : ℝ, a < b ∧ (U = Set.Ioo a b ∨ U = Set.Ioo a b \ KNatRecip)}

/-- The K-topology on `ℝ`, generated by the subbasis consisting of all sets
of the form `(a, b)` and `(a, b) \ K`, where `K = { 1/n | n ∈ ℕ+ }`. -/
@[simp]
def kTopology : TopologicalSpace ℝ :=
  TopologicalSpace.generateFrom KTopologySubbasis

/-- The generating family for the topology on `ℝ` with a basis of intervals having
rational endpoints: `Ioo a b` with `a, b ∈ ℚ` and `a < b`. -/
@[simp]
def RationalIooSubbasis : Set (Set ℝ) :=
  {U | ∃ a b : ℚ, a < b ∧ U = Set.Ioo (a : ℝ) (b : ℝ)}

/-- The topology on `ℝ` generated by the subbasis of open intervals with rational endpoints. -/
@[simp]
def realTopologyFromRationalIoo : TopologicalSpace ℝ :=
  TopologicalSpace.generateFrom RationalIooSubbasis

/-- The unit interval `[0,1]` seen as a subtype of `ℝ`. -/
@[simp] abbrev UnitInterval : Type := Set.Icc (0 : ℝ) 1

/-- The sequence of functions on the unit interval `[0,1]` given by
`(powSeqOnUnitInterval n) x = x^n`. -/
@[simp]
def powSeqOnUnitInterval : ℕ → UnitInterval → ℝ :=
  fun n x => (x : ℝ) ^ n

/-- The pointwise limit function on `[0,1]` associated with the sequence `x ↦ x^n`:
it is `0` for `x < 1` and `1` otherwise (in particular at `x = 1`). -/
@[simp]
def powLimitOnUnitInterval : UnitInterval → ℝ :=
  fun x => if (x : ℝ) < 1 then 0 else 1

/-- Pointwise convergence on a set: a sequence of functions `F : ℕ → X → β` converges
pointwise on `S` to `g : X → β` if `∀ x ∈ S, Tendsto (fun n => F n x) atTop (𝓝 (g x))`. -/
@[simp]
def PointwiseConvergesOn {X β : Type*} [TopologicalSpace β]
    (F : ℕ → X → β) (g : X → β) (S : Set X) : Prop :=
  ∀ x ∈ S, Tendsto (fun n => F n x) atTop (nhds (g x))

/-- A point `x` is a limit point (accumulation point) of a subset `A` of a topological space `X`
if every neighborhood of `x` meets `A \ {x}`. -/
@[simp]
def IsLimitPoint {X : Type*} [TopologicalSpace X] (A : Set X) (x : X) : Prop :=
  ∀ U ∈ nhds x, (U ∩ (A \ {x})).Nonempty

/-- A topological space is limit point compact if every infinite subset has a limit point. -/
@[simp]
def LimitPointCompact {X : Type*} [TopologicalSpace X] : Prop :=
  ∀ A : Set X, A.Infinite → ∃ x : X, IsLimitPoint A x

/-- A nested (decreasing) sequence `C : ℕ → Set X` of closed, nonempty sets in a
topological space:
`Antitone C ∧ (∀ n, IsClosed (C n)) ∧ (∀ n, (C n).Nonempty)`. -/
@[simp]
def NestedClosedNonempty {X : Type*} [TopologicalSpace X] (C : ℕ → Set X) : Prop :=
  Antitone C ∧ (∀ n : ℕ, IsClosed (C n)) ∧ (∀ n : ℕ, (C n).Nonempty)

/-- The property that every nested (decreasing) sequence of closed nonempty subsets of `X`
has nonempty intersection `⋂ n, C n`. -/
@[simp]
def NestedClosedNonemptyInterNonempty {X : Type*} [TopologicalSpace X] : Prop :=
  ∀ (C : ℕ → Set X),
    Antitone C →
    (∀ n : ℕ, IsClosed (C n)) →
    (∀ n : ℕ, (C n).Nonempty) →
    (⋂ n, C n).Nonempty